const users = [
  {
    id: 1,
    firstName: "Omar",
    lastName: "Faruk",
    gender: "male",
    phone: "01831342230",
    email: "omarfaruk65142@gmail.com",
  },
  {
    id: 2,
    firstName: "Shrabony",
    lastName: "Akter",
    gender: "female",
    phone: "01711223344",
    email: "shrabony@example.com",
  },
  {
    id: 3,
    firstName: "Rahim",
    lastName: "Uddin",
    gender: "male",
    phone: "01811111111",
    email: "rahim.uddin@example.com",
  },
  {
    id: 4,
    firstName: "Karima",
    lastName: "Begum",
    gender: "female",
    phone: "01722222222",
    email: "karima.begum@example.com",
  },
  {
    id: 5,
    firstName: "Sabbir",
    lastName: "Hasan",
    gender: "male",
    phone: "01833333333",
    email: "sabbir.hasan@example.com",
  },
  {
    id: 6,
    firstName: "Nusrat",
    lastName: "Jahan",
    gender: "female",
    phone: "01744444444",
    email: "nusrat.jahan@example.com",
  },
  {
    id: 7,
    firstName: "Mahmud",
    lastName: "Khan",
    gender: "male",
    phone: "01855555555",
    email: "mahmud.khan@example.com",
  },
  {
    id: 8,
    firstName: "Salma",
    lastName: "Khatun",
    gender: "female",
    phone: "01766666666",
    email: "salma.khatun@example.com",
  },
  {
    id: 9,
    firstName: "Rashed",
    lastName: "Ali",
    gender: "male",
    phone: "01877777777",
    email: "rashed.ali@example.com",
  },
  {
    id: 10,
    firstName: "Mitu",
    lastName: "Rahman",
    gender: "female",
    phone: "01788888888",
    email: "mitu.rahman@example.com",
  },
  {
    id: 11,
    firstName: "Hasan",
    lastName: "Mahmud",
    gender: "male",
    phone: "01899999999",
    email: "hasan.mahmud@example.com",
  },
  {
    id: 12,
    firstName: "Rima",
    lastName: "Akter",
    gender: "female",
    phone: "01710101010",
    email: "rima.akter@example.com",
  },
  {
    id: 13,
    firstName: "Asif",
    lastName: "Hossain",
    gender: "male",
    phone: "01812121212",
    email: "asif.hossain@example.com",
  },
  {
    id: 14,
    firstName: "Sadia",
    lastName: "Islam",
    gender: "female",
    phone: "01713131313",
    email: "sadia.islam@example.com",
  },
  {
    id: 15,
    firstName: "Jamil",
    lastName: "Chowdhury",
    gender: "male",
    phone: "01814141414",
    email: "jamil.chowdhury@example.com",
  },
  {
    id: 16,
    firstName: "Tania",
    lastName: "Sultana",
    gender: "female",
    phone: "01715151515",
    email: "tania.sultana@example.com",
  },
  {
    id: 17,
    firstName: "Rafsan",
    lastName: "Kabir",
    gender: "male",
    phone: "01816161616",
    email: "rafsan.kabir@example.com",
  },
  {
    id: 18,
    firstName: "Lamia",
    lastName: "Haque",
    gender: "female",
    phone: "01717171717",
    email: "lamia.haque@example.com",
  },
  {
    id: 19,
    firstName: "Imran",
    lastName: "Hossain",
    gender: "male",
    phone: "01818181818",
    email: "imran.hossain@example.com",
  },
  {
    id: 20,
    firstName: "Moushumi",
    lastName: "Khan",
    gender: "female",
    phone: "01719191919",
    email: "moushumi.khan@example.com",
  },
];
module.exports = { users };
